--- 
  - name: Debian family - Update apt-cache
    apt: update_cache=yes 
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Debian family - copy /etc/vimrc.local to allow cut and paste in vi
    copy:
      src: vimrc.local
      dest: /etc/vim/vimrc.local
      mode: 0644
      owner: root
      group: root
    when: ansible_distribution == 'Debian' and ansible_distribution_release != 'jessie'

  - name: Debian family - Install build tools
    apt: 
        name: ['gcc', 'g++', 'make', 'cmake', 'build-essential', 'git', 'autoconf', 'curl', 'libtool', 'libssl-dev', 'libcurl4-openssl-dev', 'libz-dev']
        state: latest
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: CentOS family - Install build tools
    yum: 
        name: ['gcc-c++', 'make', 'cmake3', 'git', 'cmake', 'autoconf', 'curl', 'libcurl-devel', 'libtool', 'openssl-devel', 'zlib-devel', 'boost-devel', 'centos-release-scl-rh']
        state: latest
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

  - name: CentOS family - Install GC 6.x
    yum:
      name: 'devtoolset-6-gcc-c++'
      state: latest
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

  - name: CentOS family - Set cmake3 as default
    alternatives:
      link: /usr/local/bin/cmake
      name: cmake
      path: /usr/bin/cmake3
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

  - name: CentOS family - Set ctest3 as default
    alternatives:
      link: /usr/local/bin/ctest
      name: ctest
      path: /usr/bin/ctest3
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

  - name: CentOS family - Set cpack3 as default
    alternatives:
      link: /usr/local/bin/cpack
      name: cpack
      path: /usr/bin/cpack3
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

  - name: CentOS family - Set ccmake3 as default
    alternatives:
      link: /usr/local/bin/ccmake
      name: ccmake
      path: /usr/bin/ccmake3
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

  - name: Debian family - Install libtool-bin
    apt: 
      name: libtool-bin 
      state: latest
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    ignore_errors: yes          

  - name: make source directory writeable
    file: path=/usr/local/src state=directory mode=0777

  - name: check out drachtio-server 
    git: repo=https://github.com/davehorton/drachtio-server.git
          dest=/usr/local/src/drachtio-server
          version={{drachtioBranch}}
          depth=50
          accept_hostkey=yes
          force=yes
    become: no
    register: checkout

  - name: CentOS family - build drachtio-server with devtoolset-6
    shell: source scl_source enable devtoolset-6 && ./autogen.sh && mkdir build && cd $_ && ../configure CPPFLAGS='-DNDEBUG' && make && sudo make install
    become: no
    args:
      executable: /bin/bash
      chdir: /usr/local/src/drachtio-server/
      creates: /usr/local/src/drachtio-server/build/drachtio
    notify: restart drachtio
    when: 
      - checkout.changed
      - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

  - name: Debian family - build drachtio-server
    shell: ./autogen.sh && mkdir build && cd $_ && ../configure CPPFLAGS='-DNDEBUG' && make && sudo make install
    become: no
    args:
      executable: /bin/bash
      chdir: /usr/local/src/drachtio-server/
      creates: /usr/local/src/drachtio-server/build/drachtio
    notify: restart drachtio
    when: 
      - checkout.changed
      - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Create drachtio log directories
    file: path="{{ item }}" state=directory
    with_items:
      - "{{ drachtioLogFileDirectory }}"
      - "{{ drachtioLogArchiveDirectory }}"
    when: checkout.changed

  - name: Create drachtio config file
    template:
      src: drachtio.conf.xml.j2
      dest: "/etc/drachtio.conf.xml"
      mode: 0644
      owner: root
      group: root
    notify: restart drachtio
    when: checkout.changed

  - name: Create drachtio systemd script
    copy: 
      src: drachtio-systemd-script
      dest: /etc/systemd/system/drachtio.service
      mode: 0744
      owner: root
      group: root
    notify: restart drachtio
    when: ansible_service_mgr == 'systemd' and checkout.changed

  - name: systemctl daemon-reload
    shell: systemctl daemon-reload
    when: ansible_service_mgr == 'systemd' and checkout.changed


